// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projector.proto

package projector;

public interface InputResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projector.InputResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input = 1;</code>
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1;</code>
   */
  com.google.protobuf.ByteString
      getInputBytes();
}
