// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projector.proto

package projector;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:projector.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
