// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projector.proto

package projector;

public final class ProjectorServiceImpl {
  private ProjectorServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projector_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projector_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projector_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projector_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projector_InputRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projector_InputRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_projector_InputResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_projector_InputResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017projector.proto\022\tprojector\"\036\n\014PowerReq" +
      "uest\022\016\n\006switch\030\001 \001(\010\"\037\n\rPowerResponse\022\016\n" +
      "\006switch\030\001 \001(\010\"\035\n\014InputRequest\022\r\n\005input\030\001" +
      " \001(\t\"\036\n\rInputResponse\022\r\n\005input\030\001 \001(\t2\232\001\n" +
      "\020ProjectorService\022B\n\013switchPower\022\027.proje" +
      "ctor.PowerRequest\032\030.projector.PowerRespo" +
      "nse\"\000\022B\n\013changeInput\022\027.projector.InputRe" +
      "quest\032\030.projector.InputResponse\"\000B#\n\tpro" +
      "jectorB\024ProjectorServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_projector_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_projector_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projector_PowerRequest_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_projector_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_projector_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projector_PowerResponse_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_projector_InputRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_projector_InputRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projector_InputRequest_descriptor,
        new java.lang.String[] { "Input", });
    internal_static_projector_InputResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_projector_InputResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_projector_InputResponse_descriptor,
        new java.lang.String[] { "Input", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
