// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermostat.proto

package thermostat;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
