// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermostat.proto

package thermostat;

public final class ThermostatServiceImpl {
  private ThermostatServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thermostat_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thermostat_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020thermostat.proto\022\nthermostat\"\036\n\014PowerR" +
      "equest\022\016\n\006switch\030\001 \001(\010\"\037\n\rPowerResponse\022" +
      "\016\n\006switch\030\001 \001(\010\")\n\022TemperatureRequest\022\023\n" +
      "\013temperature\030\001 \001(\005\"*\n\023TemperatureRespons" +
      "e\022\023\n\013temperature\030\001 \001(\0052\263\001\n\021ThermostatSer" +
      "vice\022D\n\013switchPower\022\030.thermostat.PowerRe" +
      "quest\032\031.thermostat.PowerResponse\"\000\022X\n\021ch" +
      "angeTemperature\022\036.thermostat.Temperature" +
      "Request\032\037.thermostat.TemperatureResponse" +
      "\"\0000\001B%\n\nthermostatB\025ThermostatServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_thermostat_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_thermostat_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_PowerRequest_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_thermostat_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_thermostat_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_PowerResponse_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_thermostat_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_thermostat_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_TemperatureRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_thermostat_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_thermostat_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thermostat_TemperatureResponse_descriptor,
        new java.lang.String[] { "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
