// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package printer;

public interface PrintRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.PrintRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string statement = 1;</code>
   */
  java.lang.String getStatement();
  /**
   * <code>string statement = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatementBytes();
}
