// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package printer;

public final class PrinterServiceImpl {
  private PrinterServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_PrintRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_PrintRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_PrintResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_PrintResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprinter.proto\022\007printer\"\036\n\014PowerRequest" +
      "\022\016\n\006switch\030\001 \001(\010\"\037\n\rPowerResponse\022\016\n\006swi" +
      "tch\030\001 \001(\010\"!\n\014PrintRequest\022\021\n\tstatement\030\001" +
      " \001(\t\"\"\n\rPrintResponse\022\021\n\tstatement\030\001 \001(\t" +
      "2\227\001\n\016PrinterService\022>\n\013switchPower\022\025.pri" +
      "nter.PowerRequest\032\026.printer.PowerRespons" +
      "e\"\000\022E\n\016printStatement\022\025.printer.PrintReq" +
      "uest\032\026.printer.PrintResponse\"\000(\0010\001B\037\n\007pr" +
      "interB\022PrinterServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_printer_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_printer_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_PowerRequest_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_printer_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_printer_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_PowerResponse_descriptor,
        new java.lang.String[] { "Switch", });
    internal_static_printer_PrintRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_printer_PrintRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_PrintRequest_descriptor,
        new java.lang.String[] { "Statement", });
    internal_static_printer_PrintResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_printer_PrintResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_PrintResponse_descriptor,
        new java.lang.String[] { "Statement", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
