// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public interface BrightnessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:light.BrightnessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 brightness = 1;</code>
   */
  int getBrightness();
}
