# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: projector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='projector.proto',
  package='projector',
  syntax='proto3',
  serialized_options=_b('\n\tprojectorB\024ProjectorServiceImplP\001'),
  serialized_pb=_b('\n\x0fprojector.proto\x12\tprojector\"\x1e\n\x0cPowerRequest\x12\x0e\n\x06switch\x18\x01 \x01(\x08\"\x1f\n\rPowerResponse\x12\x0e\n\x06switch\x18\x01 \x01(\x08\"\x1d\n\x0cInputRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\rInputResponse\x12\r\n\x05input\x18\x01 \x01(\t2\x9a\x01\n\x10ProjectorService\x12\x42\n\x0bswitchPower\x12\x17.projector.PowerRequest\x1a\x18.projector.PowerResponse\"\x00\x12\x42\n\x0b\x63hangeInput\x12\x17.projector.InputRequest\x1a\x18.projector.InputResponse\"\x00\x42#\n\tprojectorB\x14ProjectorServiceImplP\x01\x62\x06proto3')
)




_POWERREQUEST = _descriptor.Descriptor(
  name='PowerRequest',
  full_name='projector.PowerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='projector.PowerRequest.switch', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=60,
)


_POWERRESPONSE = _descriptor.Descriptor(
  name='PowerResponse',
  full_name='projector.PowerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='projector.PowerResponse.switch', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=93,
)


_INPUTREQUEST = _descriptor.Descriptor(
  name='InputRequest',
  full_name='projector.InputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='projector.InputRequest.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=124,
)


_INPUTRESPONSE = _descriptor.Descriptor(
  name='InputResponse',
  full_name='projector.InputResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='projector.InputResponse.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['PowerRequest'] = _POWERREQUEST
DESCRIPTOR.message_types_by_name['PowerResponse'] = _POWERRESPONSE
DESCRIPTOR.message_types_by_name['InputRequest'] = _INPUTREQUEST
DESCRIPTOR.message_types_by_name['InputResponse'] = _INPUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerRequest = _reflection.GeneratedProtocolMessageType('PowerRequest', (_message.Message,), {
  'DESCRIPTOR' : _POWERREQUEST,
  '__module__' : 'projector_pb2'
  # @@protoc_insertion_point(class_scope:projector.PowerRequest)
  })
_sym_db.RegisterMessage(PowerRequest)

PowerResponse = _reflection.GeneratedProtocolMessageType('PowerResponse', (_message.Message,), {
  'DESCRIPTOR' : _POWERRESPONSE,
  '__module__' : 'projector_pb2'
  # @@protoc_insertion_point(class_scope:projector.PowerResponse)
  })
_sym_db.RegisterMessage(PowerResponse)

InputRequest = _reflection.GeneratedProtocolMessageType('InputRequest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTREQUEST,
  '__module__' : 'projector_pb2'
  # @@protoc_insertion_point(class_scope:projector.InputRequest)
  })
_sym_db.RegisterMessage(InputRequest)

InputResponse = _reflection.GeneratedProtocolMessageType('InputResponse', (_message.Message,), {
  'DESCRIPTOR' : _INPUTRESPONSE,
  '__module__' : 'projector_pb2'
  # @@protoc_insertion_point(class_scope:projector.InputResponse)
  })
_sym_db.RegisterMessage(InputResponse)


DESCRIPTOR._options = None

_PROJECTORSERVICE = _descriptor.ServiceDescriptor(
  name='ProjectorService',
  full_name='projector.ProjectorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=159,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='switchPower',
    full_name='projector.ProjectorService.switchPower',
    index=0,
    containing_service=None,
    input_type=_POWERREQUEST,
    output_type=_POWERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='changeInput',
    full_name='projector.ProjectorService.changeInput',
    index=1,
    containing_service=None,
    input_type=_INPUTREQUEST,
    output_type=_INPUTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROJECTORSERVICE)

DESCRIPTOR.services_by_name['ProjectorService'] = _PROJECTORSERVICE

# @@protoc_insertion_point(module_scope)
