// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermostat.proto

package thermostat;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
