// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: light.proto

package light;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:light.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
